# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 517)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Monitor_Screen_32xSM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditFind = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFind.setObjectName("lineEditFind")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditFind)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBoxSched = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSched.sizePolicy().hasHeightForWidth())
        self.comboBoxSched.setSizePolicy(sizePolicy)
        self.comboBoxSched.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBoxSched.setEditable(True)
        self.comboBoxSched.setMaxCount(2147483647)
        self.comboBoxSched.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.comboBoxSched.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBoxSched.setMinimumContentsLength(60)
        self.comboBoxSched.setIconSize(QtCore.QSize(100, 16))
        self.comboBoxSched.setObjectName("comboBoxSched")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxSched)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.scheduleNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.scheduleNameLabel.setText("")
        self.scheduleNameLabel.setObjectName("scheduleNameLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.scheduleNameLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonJobs = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonJobs.setChecked(True)
        self.radioButtonJobs.setObjectName("radioButtonJobs")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonJobs)
        self.horizontalLayout.addWidget(self.radioButtonJobs)
        self.radioButtonPrecedes = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonPrecedes.setObjectName("radioButtonPrecedes")
        self.buttonGroup.addButton(self.radioButtonPrecedes)
        self.horizontalLayout.addWidget(self.radioButtonPrecedes)
        self.radioButtonFollows = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFollows.setObjectName("radioButtonFollows")
        self.buttonGroup.addButton(self.radioButtonFollows)
        self.horizontalLayout.addWidget(self.radioButtonFollows, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(638, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonQuit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonQuit.setMinimumSize(QtCore.QSize(75, 0))
        self.buttonQuit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonQuit.setObjectName("buttonQuit")
        self.horizontalLayout_3.addWidget(self.buttonQuit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionJob = QtWidgets.QAction(MainWindow)
        self.actionJob.setObjectName("actionJob")
        self.fileSchedule = QtWidgets.QAction(MainWindow)
        self.fileSchedule.setObjectName("fileSchedule")
        self.exportAction = QtWidgets.QAction(MainWindow)
        self.exportAction.setObjectName("exportAction")
        self.actionFile_Locations = QtWidgets.QAction(MainWindow)
        self.actionFile_Locations.setObjectName("actionFile_Locations")
        self.actionSetDotLoc = QtWidgets.QAction(MainWindow)
        self.actionSetDotLoc.setObjectName("actionSetDotLoc")
        self.actionShowFullSchedule = QtWidgets.QAction(MainWindow)
        self.actionShowFullSchedule.setObjectName("actionShowFullSchedule")
        self.exportFullConnectionAction = QtWidgets.QAction(MainWindow)
        self.exportFullConnectionAction.setObjectName("exportFullConnectionAction")
        self.actionShowCalendars = QtWidgets.QAction(MainWindow)
        self.actionShowCalendars.setObjectName("actionShowCalendars")
        self.fileMenu.addAction(self.actionShowFullSchedule)
        self.fileMenu.addAction(self.actionShowCalendars)
        self.fileMenu.addAction(self.exportAction)
        self.fileMenu.addAction(self.exportFullConnectionAction)
        self.menuOptions.addAction(self.fileSchedule)
        self.menuOptions.addAction(self.actionSetDotLoc)
        self.menuOptions.addAction(self.actionFile_Locations)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.buttonQuit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schedule"))
        self.label.setText(_translate("MainWindow", " Find :"))
        self.label_2.setText(_translate("MainWindow", "Select Schedule :"))
        self.label_3.setText(_translate("MainWindow", "Name :"))
        self.radioButtonJobs.setText(_translate("MainWindow", "Jobs"))
        self.radioButtonPrecedes.setText(_translate("MainWindow", "Precedes"))
        self.radioButtonFollows.setText(_translate("MainWindow", "Follows"))
        self.buttonQuit.setText(_translate("MainWindow", "Quit"))
        self.fileMenu.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionJob.setText(_translate("MainWindow", "Job"))
        self.fileSchedule.setText(_translate("MainWindow", "Set Schedule Location"))
        self.exportAction.setText(_translate("MainWindow", "Display Dependency Map"))
        self.actionFile_Locations.setText(_translate("MainWindow", "File Locations"))
        self.actionSetDotLoc.setText(_translate("MainWindow", "Set dot.exe Location"))
        self.actionShowFullSchedule.setText(_translate("MainWindow", "Show Full Schedule"))
        self.exportFullConnectionAction.setText(_translate("MainWindow", "Display Connection Map"))
        self.actionShowCalendars.setText(_translate("MainWindow", "Show Calendars"))

